abstract class MoveState {}
class InitState extends MoveState{}
class MovieModelSuccess extends MoveState{}
class MovieModelLoading extends MoveState{}
class SearchLoading extends MoveState{}
class SearchSuccess extends MoveState{}
class RecommendationSuccess extends MoveState{}
class RecommendationLoading extends MoveState{}
class PopularMoviesLoading extends MoveState{}
class PopularMoviesSuccess extends MoveState{}
class PopularMoviesError extends MoveState{}